// Generated by CoffeeScript 2.2.2
var App, AppRegistry;

import React from 'react-native';

({AppRegistry} = React);

App = require('./dist/App.js').default;

AppRegistry.registerComponent('terebinth', function() {
  return App;
});
